### ISSUE TITLE
add-apt-repository not using apt https proxy settings

### ISSUE THREAD

**Issue by baycarbone** [juju/charm-helpers#602] opened 2021-05-04 14:54 UTC
add-apt-repository does not respect the apt https proxy settings in /etc/apt/apt.conf.d/95-juju-proxy-settings
i.e.
```Acquire::https::Proxy "http://10.11.2.10:8000";```

Thus we need to revert back to using ```https_proxy``` environment variable. This behavior was changed in [#573](https://github.com/juju/charm-helpers/pull/573)

```python
    if series in ('trusty', 'xenial'):
        _run_with_retries(['add-apt-repository', '--yes', spec],
                          cmd_env=env_proxy_settings(['https', 'http']))
    else:
        _run_with_retries(['add-apt-repository', '--yes', spec])
```
=> Setting ``` cmd_env=env_proxy_settings(['https', 'http'])``` should be done in all cases.

extra references:
- [LP: #1433761](https://bugs.launchpad.net/ubuntu/+source/software-properties/+bug/1433761)
- https://fabianlee.org/2020/11/16/ubuntu-using-add-apt-repository-with-a-proxy/

**Comment by coreycb** [comment] 2021-05-04 15:10
Some related links:
https://github.com/juju/charm-helpers/commit/29c9c2c04cff4f4739caa27cd43da3bf80e40646
https://bugs.launchpad.net/ubuntu/+source/software-properties/+bug/1433761 (comment #22 is concerning)

**Comment by coreycb** [comment] 2021-05-06 19:23
I chatted with bdmurray this morning and he gave me the following reproduceder for the original issue fixed in https://github.com/juju/charm-helpers/pull/573, as seen here when testing on with a container on my local machine with the canonical VPN:

```
$ lxc launch ubuntu-daily:bionic b1
$ lxc exec b1 /bin/bash

root@b1:~# http_proxy=http://squid.internal:3128 https_proxy=http://squid.internal:3128 add-apt-repository ppa:cassandra-charmers/stable
Cannot add PPA: 'ppa:~cassandra-charmers/ubuntu/stable'.
ERROR: '~cassandra-charmers' user or team does not exist.

root@b1:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

root@b1:~# apt policy software-properties-common
software-properties-common:
  Installed: 0.96.24.32.14
  Candidate: 0.96.24.32.14
  Version table:
 *** 0.96.24.32.14 500
        500 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages
        100 /var/lib/dpkg/status
     0.96.24.32.1 500
        500 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages

root@b1:~# add-apt-repository ppa:cassandra-charmers/stable
 Dependencies required by the Cassandra charm. This PPA is referenced in the install_sources service configuration default. If it is removed, these packages need to be found in another archive listed in install_sources and install_keys.
 More info: https://launchpad.net/~cassandra-charmers/+archive/ubuntu/stable
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Hit:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease                                                                          
Hit:3 http://ppa.launchpad.net/cassandra-charmers/stable/ubuntu bionic InRelease                                                 
Hit:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease         
Hit:5 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Reading package lists... Done
```

What's interesting/confusing is that on serverstack I'm unable to recreate:
```

$ juju deploy --series bionic cs:bionic/ubuntu
$ juju ssh bionic/1

ubuntu@juju-7b084b-default-12:~$ sudo http_proxy=http://squid.internal:3128 https_proxy=http://squid.internal:3128 add-apt-repository ppa:cassandra-charmers/stable

 Dependencies required by the Cassandra charm. This PPA is referenced in the install_sources service configuration default. If it is removed, these packages need to be found in another archive listed in install_sources and install_keys.
 More info: https://launchpad.net/~cassandra-charmers/+archive/ubuntu/stable
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Hit:1 http://ppa.launchpad.net/cassandra-charmers/stable/ubuntu bionic InRelease
Hit:2 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:3 http://nova.clouds.archive.ubuntu.com/ubuntu bionic InRelease
Hit:4 http://nova.clouds.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:5 http://nova.clouds.archive.ubuntu.com/ubuntu bionic-backports InRelease
Reading package lists... Done

ubuntu@juju-7b084b-default-12:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

ubuntu@juju-7b084b-default-12:~$ apt policy software-properties-common
software-properties-common:
  Installed: 0.96.24.32.14
  Candidate: 0.96.24.32.14
  Version table:
 *** 0.96.24.32.14 500
        500 http://nova.clouds.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages
        100 /var/lib/dpkg/status
     0.96.24.32.1 500
        500 http://nova.clouds.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
```

**Comment by coreycb** [comment] 2021-05-06 20:05
I keep going back to this comment in the software-properties bug: https://bugs.launchpad.net/ubuntu/+source/software-properties/+bug/1433761/comments/22

Bayani, by any chance can you confirm the statement in that comment in your environment? For example, attempting the add-apt-repository call with with various combinations of Acquire::https::Proxy and Acquire::http::Proxy in  /etc/apt/apt.conf.d/95-juju-proxy-settings? As well as with combinations of https_proxy=<https-proxy-url> and http_proxy=<https-proxy-url> prepended to the add-apt-repository call?

**Comment by coreycb** [comment] 2021-05-10 18:25
For the test from bdmurray, I hit the same error on xenial and trusty:

```
root@x1:~# http_proxy=http://squid.internal:3128 https_proxy=http://squid.internal:3128 add-apt-repository ppa:cassandra-charmers/stable
Cannot add PPA: 'ppa:~cassandra-charmers/ubuntu/stable'.
ERROR: '~cassandra-charmers' user or team does not exist.
root@x1:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.7 LTS
Release:        16.04
Codename:       xenial

root@t1:~# http_proxy=http://squid.internal:3128 https_proxy=http://squid.internal:3128 add-apt-repository ppa:cassandra-charmers/stable
Cannot add PPA: 'ppa:cassandra-charmers/stable'.
Please check that the PPA name or format is correct.
root@t1:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.6 LTS
Release:        14.04
Codename:       trusty
```

**Comment by coreycb** [comment] 2021-05-10 19:16
Digging some more, it looks like the "Cannot add PPA" error just means that the proxy is doing it's job and has denied access to the PPA:
Cannot add PPA: 'ppa:~cassandra-charmers/ubuntu/stable'.
ERROR: '~cassandra-charmers' user or team does not exist.

For example, testing with a squid proxy that is configured to deny all requests from localhost hits the same error:
```
$ lxc launch ubuntu-daily:bionic b1
$ lxc exec b1 /bin/bash
root@b1:~# sudo apt install --yes squid
root@b1:~# sed -i 's/http_access allow localhost/#http_access allow localhost/g' /etc/squid/squid.conf  # deny access from localhost
root@b1:~# sudo systemctl restart squid
root@b1:~# http_proxy=http://127.0.0.1:3128 https_proxy=http://127.0.0.1:3128 add-apt-repository ppa:cassandra-charmers/stable
Cannot add PPA: 'ppa:~cassandra-charmers/ubuntu/stable'.
ERROR: '~cassandra-charmers' user or team does not exist.
```

**Comment by coreycb** [comment] 2021-05-10 20:49
Some more details for other releases to test behavior of the software-properties package. I wanted to test these before removing the comment in the code. These should fail if going through the proxy because the proxy denies requests from local host. So it seams the apt.conf.d settings don't take effect and go through the proxy.

xenial
```
root@x1:~# grep Proxy /etc/apt/apt.conf.d/95-juju-proxy-settings
Acquire::http::Proxy "http://127.0.0.1:3128";
Acquire::https::Proxy "http://127.0.0.1:3128";
root@x1:~# add-apt-repository ppa:cassandra-charmers/stable
 Dependencies required by the Cassandra charm. This PPA is referenced in the install_sources service configuration default. If it is removed, these packages need to be found in another archive listed in install_sources and install_keys.
 More info: https://launchpad.net/~cassandra-charmers/+archive/ubuntu/stable
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keyring `/tmp/tmpfm8xyaq9/secring.gpg' created
gpg: keyring `/tmp/tmpfm8xyaq9/pubring.gpg' created
gpg: requesting key D4CF1C1E from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpfm8xyaq9/trustdb.gpg: trustdb created
gpg: key D4CF1C1E: public key "Launchpad PPA for Cassandra Charmers" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK

root@x1:~# http_proxy=http://squid.internal:3128 https_proxy=http://squid.internal:3128 add-apt-repository ppa:cassandra-charmers/stable
Cannot add PPA: 'ppa:~cassandra-charmers/ubuntu/stable'.
ERROR: '~cassandra-charmers' user or team does not exist.
```

bionic
```
root@b1:~# grep Proxy /etc/apt/apt.conf.d/95-juju-proxy-settings
Acquire::http::Proxy "http://127.0.0.1:3128";
Acquire::https::Proxy "http://127.0.0.1:3128";
root@b1:~# add-apt-repository --no-update ppa:cassandra-charmers/stable
 Dependencies required by the Cassandra charm. This PPA is referenced in the install_sources service configuration default. If it is removed, these packages need to be found in another archive listed in install_sources and install_keys.
 More info: https://launchpad.net/~cassandra-charmers/+archive/ubuntu/stable
Press [ENTER] to continue or Ctrl-c to cancel adding it.

root@b1:~# http_proxy=http://squid.internal:3128 https_proxy=http://squid.internal:3128 add-apt-repository --no-update ppa:cassandra-charmers/stable
Cannot add PPA: 'ppa:~cassandra-charmers/ubuntu/stable'.
ERROR: '~cassandra-charmers' user or team does not exist.
```

focal
```
root@f1:~# grep Proxy /etc/apt/apt.conf.d/95-juju-proxy-settings
Acquire::http::Proxy "http://127.0.0.1:3128";
Acquire::https::Proxy "http://127.0.0.1:3128";
root@f1:~# add-apt-repository --no-update ppa:cassandra-charmers/stable
 Dependencies required by the Cassandra charm. This PPA is referenced in the install_sources service configuration default. If it is removed, these packages need to be found in another archive listed in install_sources and install_keys.
 More info: https://launchpad.net/~cassandra-charmers/+archive/ubuntu/stable
Press [ENTER] to continue or Ctrl-c to cancel adding it.

root@f1:~# http_proxy=http://squid.internal:3128 https_proxy=http://squid.internal:3128 add-apt-repository --no-update ppa:cassandra-charmers/stable
Cannot add PPA: 'ppa:~cassandra-charmers/ubuntu/stable'.
ERROR: '~cassandra-charmers' user or team does not exist.
```

**Closed** 2021-05-12 21:54 UTC
